#!/bin/bash

apt-get -y update
apt-get -y upgrade

cd /mnt/server/garrysmod/cfg
rm -r mount.cfg

echo '
"mountcfg"
{
	"cstrike"	"/home/container/cstrike"
//	"tf"		"C:\mytf2server\tf"
}
' > mount.cfg

cd /mnt/server

apt-get install -y wget

wget hhtps://archive.horizonnetworks.uk/Resources/Pterodactyl%20Mods/css.zip

apt install -y zip
apt install -y unzip

unzip css.zip

rm -r css.zip
